### ISSUE TITLE
Deployere skallapplikasjon til fly.oi

### ISSUE THREAD

**Issue by ksvedal** [felleslosninger/dc24-eu-wallet#6]
Oppgåva omfatter:

- Sette opp docker (eller noko lignande)
- fly.toml
- teste at den fungerer (og at deployment fungerer som det skal)
- Alternativt prøve å få til automatisk bygging og deployment ved push til main (?)

**Comment by DanielNeset** [comment]
CD/CD pipeline using workflow to build and deploy application to fly has been set up and working as intended
